version: '3.4'
services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
  messagebroker:
    image: rabbitmq:management
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/CatalogAPI/Dockerfile
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  yarpapigatway:
    image: ${DOCKER_REGISTRY-}yarpapigatway
    build:
      context: .
      dockerfile: src/ApiGatways/YarpApiGatway/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:




